Pagination refactoring
src-d/metadata-retrieval pull request #41
Opened 2019-10-11 10:47 UTC by smacker

Fix: #12
Based on: #34 (last 2 new commits are new)

This PR removes duplicated code and reduces the number of hard-coded string in the code.
In terms of lines diff:
```
2 files changed, 393 insertions(+), 614 deletions(-)
```
But more importantly, it's harder to make a mistake as downloading connections is unified.

---

* [ ] I have updated the CHANGELOG file according to the conventions in [keepachangelog.com](https://keepachangelog.com)
* [x] This PR contains changes that do not require a mention in the CHANGELOG file

2019-10-15 16:27 UTC, smacker commented
rebased on master

2019-10-16 10:24 UTC, se7entyse7en requested changes
some little changes 👏

2019-10-16 11:07 UTC, smacker commented on github/downloader.go
> +	isLoggable := t == issuesType || t == pullRequestsType || t == membersWithRole
Is this ok? https://github.com/src-d/metadata-retrieval/pull/41/commits/732fa1325870279de47daddc4f04fcb03bfcc692

2019-10-16 11:10 UTC, smacker commented on github/downloader.go
> +		if isLoggable && count%int(t.PageSize) == 0 {
I made it log each page. As now we use max limit 100, it should be fine.

2019-10-16 12:03 UTC, se7entyse7en approved these changes
Thanks!

2019-10-16 12:55 UTC, merged